import android from '././src/assets/tools/android.svg'
import angular from '././src/assets/tools/angular.svg'
import AntDesign from '././src/assets/tools/AntDesign.svg'
import appium from '././src/assets/tools/appium.svg'
import Aws from '././src/assets/tools/Aws.svg'
import azure from '././src/assets/tools/azure.svg'
import balsamic from '././src/assets/tools/balsamic.svg'
import bitButket from '././src/assets/tools/bitButket.svg'
import cassandra from '././src/assets/tools/cassandra.svg'
import cypress from '././src/assets/tools/cypress.svg'
import digitalOcean from '././src/assets/tools/digitalOcean.svg'
import docker from '././src/assets/tools/docker.svg'
import Els from '././src/assets/tools/Els.svg'
import figma from '././src/assets/tools/figma.svg'
import flutter from '././src/assets/tools/flutter.svg'
import gcp from '././src/assets/tools/GCP.svg'
import gitLab from '././src/assets/tools/gitLab.svg'
import go from '././src/assets/tools/go.svg'
import grafana from '././src/assets/tools/grafana.svg'
import illustrator from '././src/assets/tools/illustrator.svg'
import invision from '././src/assets/tools/invision.svg'
import ios from '././src/assets/tools/ios.svg'
import Java from '././src/assets/tools/Java.svg'
import jmeter from '././src/assets/tools/jmeter.svg'
import js from '././src/assets/tools/js.svg'
import kotlin from '././src/assets/tools/kotlin.svg'
import kubernetes from '././src/assets/tools/kubernetes.svg'
import materialUi from '././src/assets/tools/materialUi.svg'
import mongodb from '././src/assets/tools/mongodb.svg'
import Next from '././src/assets/tools/Next.svg'
import nodejs from '././src/assets/tools/nodejs.svg'
import php from '././src/assets/tools/php.svg'
import principle from '././src/assets/tools/principle.svg'
import Promet from '././src/assets/tools/Promet.svg'
import python from '././src/assets/tools/python.svg'
import React from '././src/assets/tools/React.svg'
import sass from '././src/assets/tools/sass.svg'
import sketch from '././src/assets/tools/sketch.svg'
import Sql from '././src/assets/tools/Sql.svg'
import Swift from '././src/assets/tools/Swift.svg'
import vue from '././src/assets/tools/vue.svg'
import youtrack from '././src/assets/tools/youtrack.svg'
import zeplin from '././src/assets/tools/zeplin.svg'


export {android, zeplin, youtrack, vue, Swift, Sql, sass,
     sketch, React, php,
      principle, python, Promet, nodejs, Next, materialUi, mongodb, 
      kubernetes, kotlin, jmeter,
       js, Java, illustrator, invision,
        ios, gcp, gitLab, grafana, go, Els, flutter, figma, 
        cassandra,cypress, digitalOcean, docker, angular, appium, azure, AntDesign, Aws, balsamic, bitButket }